first_proj/first_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^personal$', include('personal.urls')),
    url(r'^music/', include('music.urls')),
]

first_proj/music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'

urlpatterns = [
	# /music/
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    # # /music/420
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # # /music/420/favorite
    # url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),


    # # /music/album/add
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # # /music/album/2
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # # /music/album/2/delete
    # url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

first_proj/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title+' - '+self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

first_proj/music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

class IndexView(generic.ListView):
	template_name="music/index.html"
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model=Album
	template_name="music/detail.html"


class AlbumCreate(CreateView):
	model = Album
	fields=['artist', 'album_title', 'genre', 'album_logo']
	
class AlbumUpdate(UpdateView):
	model = Album
	fields=['artist', 'album_title', 'genre', 'album_logo']
	
class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

first_proj/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Song Django Tut{% endblock %}
	
{% block body %}
	<!-- <img src="{{album.album_logo}}" height="50%"> -->

<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}

	{% include 'music/form-template.html' %}

	<div class="form-group">
		<div class="col-sm-offfset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
		
	</div>


</form>

{% endblock %}

first_proj/music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
	{% block title %}
		Django Tut
	{% endblock %}
	</title>
	<!-- load static files -->
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- external css and js -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled and minified CSS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="{% url 'music:index' %}" class="navbar-brand">Home Logo</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse" id="topNavBar">

			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value=""/>
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
					</a>
				</li>
			</ul>


		</div>



	</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

first_proj/music/templates/music/detail-old.html
{% extends 'music/base.html' %}
{% block title %}Song Django Tut{% endblock %}
	
{% block body %}
	<!-- <img src="{{album.album_logo}}" height="50%"> -->

	<h1>{{album.album_title}}</h1>
	<h3>{{album.artist}}</h3>

	<ul>
		{% for song in album.song_set.all %}
			<li>{{ song.song_title }} - {{ song.file_type }}</li>
		{% endfor %}
	</ul>

	{% if error_message %}
		Error {{error_message}}
	{% endif %}
	<form method="post" action="{% url 'music:favorite' album.id %}">
		{% csrf_token %}	
		{% for song in album.song_set.all %}
			<input type="radio" name="song" id="song{{song.id}}" value="{{song.id}}" />
			<label for="song{{song.song_title}}">{{song.song_title}}</label>
			{% if song.is_favorite %}
			Favorite
			{% endif %}
		{% endfor %}
		<input type="submit" name="song_favorite" id="Favorite">
	</form>
{% endblock %}

first_proj/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Song Django Tut{% endblock %}
	
{% block body %}
	<!-- <img src="{{album.album_logo}}" height="50%"> -->

	<h1>{{album.album_title}}</h1>
	<h3>{{album.artist}}</h3>

	<ul>
		{% for song in album.song_set.all %}
			<li>{{ song.song_title }} - {{ song.file_type }}</li>
		{% endfor %}
	</ul>

{% endblock %}

first_proj/music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offfset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

first_proj/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
	{% if all_albums %}
	<h2>Here all my albums</h2>
	<ul>
		{% for album in all_albums %}
		<!-- <li><a href="/music/{{album.id}}/">{{album.album_title}}</a></li>	 --><!-- Old format with hardcoded url, so changing it to dynamic -->
		<li>
			<a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a> -
			<a href="{% url 'music:album-update' album.id %}">Edit</a>
			<a href="{% url 'music:album-delete' album.id %}">Delete</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<h3>No albums</h3>
	{% endif %}
{% endblock %}